on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pre-commit
      run: |
        python -m pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
