on:
    workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: super-linter/super-linter@v6.5.0
        env:
          SUPERLINT_TOKEN: ${{ secrets.SUPERLINT_TOKEN }}